# Generated by Django 3.2 on 2023-03-29 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notify_token',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator('([a-z]|[A-Z]|[0-9])\\w+', 'Notify token is not valid', 'invalid')], verbose_name='Notification Token'),
        ),
    ]
