# Generated by Django 3.2 on 2023-03-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='package',
            table='packages',
        ),
    ]
